upi_features:
  - amount
  - oldbalanceOrg
  - newbalanceOrig
  - oldbalanceDest
  - newbalanceDest
  - amount_log
  - orig_balance_change
  - dest_balance_change
  - balance_mismatch_orig
  - balance_mismatch_dest
  - orig_zero_but_amount
  - dest_zero_but_amount
  - orig_balance_ratio
  - dest_balance_ratio
  - type_CASH_IN
  - type_CASH_OUT
  - type_DEBIT
  - type_PAYMENT
  - type_TRANSFER
  - sender_amount_mean
  - sender_amount_std
  - sender_amount_max
  - sender_tx_count
  - sender_balance_mismatch_ratio
  - sender_zero_but_ratio
  - dest_amount_mean
  - dest_amount_std
  - dest_tx_count
  - dest_zero_but_ratio
  - tx_per_step_orig
  - amount_per_step_orig
  - avg_amount_per_step_orig
  - balance_gap_ratio
  - relative_amount_to_mean_sender
  - amount_to_balance_orig_ratio
  - amount_balance_gap
  - is_large_transfer
  - is_same_sender_receiver
  - is_merchant_dest
  - is_customer_dest
  - amount_to_sender_mean_ratio
  - amount_to_balance_gap_ratio
  - sender_activity_intensity
  - type_encoded
